#server:
#  port: 8082
#
#spring:
#
#  datasource:
#    url: jdbc:postgresql://localhost:5433/bhyt
#    username: postgres
#    password: minhngoc
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
